workflows:
  ios-build:
    name: Build iOS
    max_build_duration: 60
    scripts:
      - name: Set up project
        script: |
          brew install xcodegen swiftlint swiftformat git-lfs pkl sourcery swiftgen
          xcrun simctl list devices available
      
      - name: Generate Xcode project
        script: |
          xcodegen generate
      
      - name: Build
        script: |
          xcodebuild -project ElementX.xcodeproj \
            -scheme ElementX \
            -configuration Debug \
            CODE_SIGNING_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            -destination 'generic/platform=iOS Simulator' \
            build
    artifacts:
      - /tmp/xcodebuild_logs/*.log
      - build/**/*.app
