workflows:
  ios-build:
    name: Build iOS
    max_build_duration: 60
    environment:
      xcode: "16.1"
      flutter: "latest"
    scripts:
      - name: Set up project
        script: |
          brew install xcodegen swiftlint swiftformat git-lfs pkl
          
      - name: Generate Xcode project
        script: |
          xcodegen generate
          
      - name: Build
        script: |
          xcodebuild -project ElementX.xcodeproj \
            -scheme ElementX \
            -configuration Debug \
            CODE_SIGNING_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            -destination 'generic/platform=iOS Simulator' \
            build
    artifacts:
      - /tmp/xcodebuild_logs/*.log
