name: Build iOS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app
      
      - name: Build
        run: xcodebuild -project ElementX.xcodeproj -scheme ElementX -configuration Release build CODE_SIGNING_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ElementX
          path: build/*.ipa
